name: Deploy Vue 3 App with Vite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Verify Repository Structure
        run: ls -la

      - name: Move into Project Directory
        run: cd openchs-site && ls -la

      - name: Install Dependencies
        run: npm ci
        working-directory: openchs-site # Ensure commands run in the right directory

      - name: Build Project
        run: npm run build
        working-directory: openchs-site

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: openchs-site/dist # Uploads the built files
